baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Matthew Liu'
theme = 'looliu'
sectionPagesMenu = 'main'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'